### ISSUE TITLE
Negation regex [^abc] works to oppossite

### ISSUE THREAD

**Issue by RV2013** [pieceofsummer/WTReTextField#2]
Hi,
First of all, I would like to thank you for making such a nice piece of code which comes handy for building a quality iOS apps in production.
The issue is when I use pattern as ' @"^([^qvx]){4}$" ', the ETRexTextField should not let user type in any word from set Q,V or X but contrary to that, the textfield only accepts these 3 characters only from A-Z and rest are ignored.

Please help me OR guide me to make this possible with WTReTextField.

Thanks in Advance !

**Comment by pieceofsummer** [comment]
Just pushed a fix. There was a mistype in the negation code.
