### ISSUE TITLE
Credit Card Validator

### ISSUE THREAD

**Issue by hightech** [pieceofsummer/WTReTextField#3]
Hi,
Are you going to add 4 digits in CW code and "4 digits 6 digits 5 digits" in credit card number for American Express? It would be nice to have both "4 groups of 4 digits separated by space" and "4 digits 6 digits 5 digits" in credit card numbers and also 4 or 3 digits in CW code, so we can detect which card is American Express or Visa, etc.. on specific number of digits in card number.

Thanks!

**Comment by pieceofsummer** [comment]
Credit card mask is not hard-coded in the source. Just write the regular expression you need, and the control will use it.

It is better to detect proper format (card type) not by length (it is unknown while you're typing), but by first few digits. American Express number always starts with 34 or 37, Visa starts with 4, MC starts with 50-55, etc. More detailed rules are explained [here](http://en.wikipedia.org/wiki/Bank_card_number#Issuer_identification_number_.28IIN.29).
For example, you can write the following expression to format American Express and others differently: 

```
editor.pattern = "^(3[47]\\d{2}(?: )\\d{5}(?: )\\d{6}|[456]\\d{3}((?: )\\d{4}){3})$";
```

**Comment by hightech** [comment]
@pieceofsummer  Awesome! It is working so well. Thank you so much!
